FROM mcr.microsoft.com/mssql/server:2022-latest
WORKDIR /usr/src/app
USER root

COPY ./initdb/run.sh /usr/src/app
COPY ./initdb/entrypoint.sh /usr/src/app
COPY ./initdb/setup.sql /usr/src/app
RUN chown mssql:mssql /usr/src/app
RUN chmod 777 ./run.sh 
RUN chmod 777 ./entrypoint.sh 
RUN chmod 777 ./setup.sql 
ENV SA_PASSWORD Qwerty-1
ENV ACCEPT_EULA Y


EXPOSE 1433
USER mssql
CMD /bin/bash ./entrypoint.sh